apiVersion: v1
kind: ReplicationController
metadata:
  name: docker-registry
  labels:
    name: docker-registry
    tier: backend
spec:
  replicas: 1
  selector:
    name: docker-registry
  template:
    metadata:
      labels:
        name: docker-registry
        tier: backend
    spec:
      containers:
        - name: docker-registry
          image: registry:2
          ports:
            - containerPort: 5000
              name: registry
          env:
          - name: VIRTUAL_HOST
            value: nectar-registry.kolibri.is
          volumeMounts:
              # This name must match the volumes.name below.
            - name: docker-registry-data
              mountPath: /var/lib/docker
      volumes:
        - name: docker-registry-data
          awsElasticBlockStore:
            volumeID: "aws://KUBE_AWS_ZONE/AWS_DATA_VOLUME_ID"
            fsType: ext4
