apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    name: docker-registry
spec:
  type: LoadBalancer
  loadBalancerIP: "52.17.56.160"
  ports:
    # the port that this service should serve on
  - port: 80
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    name: docker-registry
    tier: backend