apiVersion: v1
kind: ReplicationController
metadata:
  name: go-server
  labels:
    name: go-server
    tier: backend
spec:
  replicas: 1
  selector:
    name: go-server
  template:
    metadata:
      labels:
        name: go-server
        tier: backend
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: gocd
          image: gocd/gocd-server
          ports:
            - containerPort: 8153
              name: gocd
            - containerPort: 8154
              name: gocd-agents
          env:
          - name: AGENT_KEY
            value: HithereKolibriWasHer3
          - name: MSG_TIME
            value: "0"
          volumeMounts:
              # This name must match the volumes.name below.
        #    - name: gocd-persistent-storage
        #      mountPath: /var/lib/go-server
        #    - name: gocd-persistent-config
        #      mountPath: /etc/go
            - name: passwords-nectar-cd-kolibri-is
              mountPath: /etc/secrets
      volumes:
        - name: passwords-nectar-cd-kolibri-is
          secret:
            secretName: passwords-nectar-cd-kolibri-is

        #- name: gocd-persistent-storage
        #  awsElasticBlockStore:
        #    volumeID: "aws://KUBE_AWS_ZONE/AWS_DATA_VOLUME_ID"
        #    fsType: ext4
        #- name: gocd-persistent-config
        #  awsElasticBlockStore:
        #    volumeID: "aws://KUBE_AWS_ZONE/AWS_CONFIG_VOLUME_ID"
        #    fsType: ext4
