apiVersion: v1
kind: Service
metadata:
  name: go-server
  labels:
    name: go-server
spec:
  ports:
    # the port that this service should serve on
  - port: 8153
    protocol: TCP
    name: gocd-server
  - port: 8154
    protocol: TCP
    name: gocd-agent-listen
  selector:
    name: go-server
    tier: backend