apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nectar
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: nectar
    tier: frontend
  externalIPs:
    - "146.148.12.189"
