apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    name: jenkins
    tier: backend