apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
    tier: backend
spec:
  replicas: 1
  selector:
    name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
        tier: backend
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
              # This name must match the volumes.name below.
            - name: rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-persistent-storage
          gcePersistentDisk:
            # This disk must already exist.
            pdName: nectar-rabbitmq-data
            fsType: ext4